# Generated by Django 3.2.13 on 2022-10-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precisionmedicine', '0002_auto_20221025_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[(1, 'M'), (2, 'F'), (3, 'O')], max_length=1)),
                ('protine', models.CharField(max_length=8)),
            ],
        ),
    ]
