# Generated by Django 3.2.13 on 2022-10-29 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('precisionmedicine', '0005_patient_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disaese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('root_protine', models.CharField(max_length=8)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='precisionmedicine.patient')),
            ],
        ),
    ]
